name: dg3n_build
channels:
  - defaults
  - conda-forge
  - anaconda
  - nrel
dependencies:
  - colorama
  - colorlog
  - requests
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - psutil
  - psycopg2
  - scipy
  - spyder
  - sqlalchemy
  - nrel-pysam=4.2.0
  - pip:
    - nrel-pysam-stubs