-- IN PREVIOUS MODEL ITERATIONS, THERE WERE GRID POINTS
-- FOR WHICH WE DID NOT HAVE WIND SPEED TMY DATA FROM AWS.

-- THE SCRIPTS IN THIS FOLDER ARE USED TO ISOLATE THE POINTS
-- WITH THAT ISSUE AND ASSIGN THEM A REPRESENTATIVE NEARBY TMY 
-- FILE.

-- IN THE MOST RECENT MODEL ITERATION (Feb 23, 2015), 
-- THIS ISSUE DID NOT EXIST, SO THE MAJORITY OF THESE SCRIPTS DON'T NEED TO BE RUN.

--  TO DETERMINE IF THESE SCRIPTS ARE NECESSARY IN THE FUTURE,
-- OPEN THEM UP AND RUN THE FIRST QUERY. IF ZERO ROWS ARE RETURNED, 
-- SKIP TO THE BOTTOM OF THE SQL FILE ONLY RUN THE QUERIES IN THE FINAL BLOCK. OTHERWISE,
-- RUN THE ENTIRE SCRIPT EXCEPT FOR THE FINAL BLOCK.