name: docker-compose-actions-workflow
on:
  push:
  pull_request:
jobs:

  docker_compose:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    name: Tests Dockerfile 
    container: docker

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Install rsync
        run: apk update && apk add --no-cache rsync

      - name: create data directory
        working-directory: ./
        run: |
          mkdir -p ./docker_actions/
          chmod 755 ./docker_actions/
          ls -ld ./docker_actions/
          ls -l ./docker_actions/

          rsync -a .github/docker_actions/ ./docker_actions/
          rsync -a --exclude='input_sheet_final.xlsm' --exclude='docker-compose.yml' ./docker/ ./docker_actions/
          ls -l ./docker_actions/docker-compose.yml
          cat ./docker_actions/docker-compose.yml
          ls -l ./docker_actions/dgen/input_sheet_final.xlsm
          md5sum ./docker_actions/dgen/input_sheet_final.xlsm

          rm -rf ./docker_actions/dgen_data/
          rm -rf ./docker_actions/postgresql_data/
          mkdir -p ./docker_actions/dgen_data/
          chmod 755 ./docker_actions/dgen_data/
          chown -R 999:999 ./docker_actions/dgen_data/
          ls -ld ./docker_actions/dgen_data/
          ls -l ./docker_actions/dgen_data/

      - name: "Builds the docker composed image and the docker compose"
        id: build
        working-directory: ./docker_actions/
        run: |
          docker compose down
          docker system prune -a -f # remove all stopped containers and dangling images
          docker compose up --build -d
      
      - name: "Pause for database to finish set up"
        run: |
          docker compose up --abort-on-container-exit 
          docker attach test_dgen
          exit
        
      # - name: "pause for database to finish set up"
      #   shell: bash
      #   run: |
      #     echo sleeping now
      #     sleep 30s
      #     exit
        

      # - name: run python script
      #   working-directory: ./docker_actions/dgen
      #   run: |
      #     sleep 300s
      #     echo "sleeping"
      #     python dgen_model.py
          
          

      # - name: connect to containers
      #   run: docker attach dgen_5
      # - name: "Brings up the docker compose and runs the tests"
      #   id: run-test
      #   run: docker compose up --abort-on-container-exit --exit-code-from client

      # - name: Test
      #   run: docker run --network container:webapp-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
